api_platform:
  title: GuideHub API
  version: 1.0.0
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
      X-Locale:
        name: X-Locale
        type: header
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    formats:
      json: ['application/json']
      jsonld: ['application/ld+json']
    docs_formats:
      html: ['text/html']
  use_symfony_listeners: true
